### ISSUE TITLE
AttributeError: 'str' object has no attribute 'create_ffmpeg_player'

### ISSUE THREAD

**Issue by Laffini** [mephasor/mephaBot#3]
I keep getting this problem?

```
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Laffy\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\Users\Laffy\Desktop\FragBot\mephaBot-master\runBot.py", line 88, in on_message
    rtrn = await self.commands[key](self, message)
  File "C:\Users\Laffy\Desktop\FragBot\mephaBot-master\addons\onlineRadio.py", line 97, in botPlayRadio
    client.player = voice.create_ffmpeg_player(radioUrl)
AttributeError: 'str' object has no attribute 'create_ffmpeg_player'
```

**Comment by mephasor** [comment]
Are you sure that ffmpeg ist installed?

**Comment by Laffini** [comment]
Yes
