### ISSUE TITLE
process gets killed  and restarts

### ISSUE THREAD

**Issue by FakeShell** [mephasor/mephaBot#7]
hello
ive been trying to run this bot and when i added the station and discord token and configured everything when i try to run it i get this 
Traceback (most recent call last):
  File "runBot.py", line 16, in <module>
    discord.opus.load_opus('/usr/local/lib/libopus.so')
  File "/usr/local/lib/python3.5/dist-packages/discord/opus.py", line 156, in load_opus
    _lib = libopus_loader(name)
  File "/usr/local/lib/python3.5/dist-packages/discord/opus.py", line 83, in libopus_loader
    lib = ctypes.cdll.LoadLibrary(name)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 429, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/libopus.so: cannot open shared object file: No such file or directory
Restarting bot...
any ideas?
i have all dependencies installed and everything updated

**Comment by mephasor** [comment]
Hi there. 
I haven't updated the bot in quite a while since there is a large number of more convenient bots out there.
Just from the looks of it, it is looking for libopus, but cannot find it. Maybe try installing that one?

**Comment by BardiaMGTGC** [comment]
after installing opus-tools and opus-dev looks like i still have the issue
i was thinking about getting the shared library file and just putting it in /usr/local/lib
is there anywhere i can get the file(only the file) or do i need to compile it myself

**Comment by FakeShell** [comment]
you were right i got it to work after compiling opus encoder
thanks

**Comment by mephasor** [comment]
Perfect! Let me know if anything else pops up.
